"use strict";
let beautiful_sights = ["Makkah", "Kashmir", "Switzerland", "London", "Yemen"];
console.log(beautiful_sights);
let beautiful_sights1 = beautiful_sights.slice(0);
console.log(beautiful_sights1.sort());
console.log(beautiful_sights);
console.log(beautiful_sights1.sort().reverse());
console.log(beautiful_sights);
console.log(beautiful_sights1.reverse());
console.log(beautiful_sights1.reverse());
console.log(beautiful_sights);
console.log(beautiful_sights1.sort());
console.log(beautiful_sights1.sort().reverse());
